package main

import (
	"github.com/gin-gonic/gin"

	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"

	_ "github.com/pashukhin/indriver-test-task/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title inDriver test task
// @version 1.0
// @description Implementation of inDriver test task.

// @contact.name Grigoriy Pashukhin
// @contact.url https://github.com/pashukhin

// @host localhost:8080
// @BasePath /
func main() {
	r := gin.Default()

	swaggerUrl := ginSwagger.URL("http://localhost:8080/swagger/doc.json")
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, swaggerUrl))

	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run() // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
}
