basePath: /
host: localhost:8080
info:
  contact:
    name: Grigoriy Pashukhin
    url: https://github.com/pashukhin
  description: Implementation of inDriver test task.
  license: {}
  title: inDriver test task
  version: "1.0"
paths: {}
swagger: "2.0"
